USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE WALMART_DB;

CREATE OR REPLACE SCHEMA WALMART_DB.RAW;


CREATE OR REPLACE STORAGE INTEGRATION WALMART_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::568318157863:role/walmart_mysnowflakerole'
    STORAGE_ALLOWED_LOCATIONS = ('s3://walmart-data-e2e-sd/data/');

DESC INTEGRATION WALMART_INT; -- update the trust policy of the IAM role 

CREATE OR REPLACE STAGE WALMART_DB.RAW.WALMART_STAGE
    STORAGE_INTEGRATION = WALMART_INT
    URL = 's3://walmart-data-e2e-sd/data/';

ls @WALMART_DB.RAW.WALMART_STAGE; -- confirm all three source datasets are present

CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null')
  EMPTY_FIELD_AS_NULL = true;

CREATE OR REPLACE TABLE WALMART_DB.RAW.FACT
(
    STORE          VARCHAR,
    DATE           VARCHAR,
    TEMPERATURE    VARCHAR,
    FUEL_PRICE     VARCHAR,
    MARKDOWN1      VARCHAR,
    MARKDOWN2      VARCHAR,
    MARKDOWN3      VARCHAR,
    MARKDOWN4      VARCHAR,
    MARKDOWN5      VARCHAR,
    CPI            VARCHAR,
    UNEMPLOYMENT   VARCHAR,
    ISHOLIDAY      VARCHAR
);

COPY INTO WALMART_DB.RAW.FACT (
    STORE,
    DATE,
    TEMPERATURE,
    FUEL_PRICE,
    MARKDOWN1,
    MARKDOWN2,
    MARKDOWN3,
    MARKDOWN4,
    MARKDOWN5,
    CPI,
    UNEMPLOYMENT,
    ISHOLIDAY
)
FROM @WALMART_DB.RAW.WALMART_STAGE
FILES = ('fact.csv') -- must indicate respective file for table in s3 bucket
FILE_FORMAT = (FORMAT_NAME = 'MY_CSV_FORMAT')
ON_ERROR = 'SKIP_FILE';

CREATE OR REPLACE TABLE WALMART_DB.RAW.DEPARTMENT
(
    STORE          VARCHAR,
    DEPT           VARCHAR,
    DATE           VARCHAR,
    WEEKLY_SALES   VARCHAR,
    ISHOLIDAY      VARCHAR
);

COPY INTO WALMART_DB.RAW.DEPARTMENT (
    STORE,
    DEPT,
    DATE,
    WEEKLY_SALES,
    ISHOLIDAY
)
FROM @WALMART_DB.RAW.WALMART_STAGE
FILES = ('department.csv') -- must indicate respective file for table in s3 bucket
FILE_FORMAT = (FORMAT_NAME = 'MY_CSV_FORMAT')
ON_ERROR = 'SKIP_FILE';

CREATE OR REPLACE TABLE WALMART_DB.RAW.STORES
(
    STORE          VARCHAR,
    TYPE           VARCHAR,
    SIZE           VARCHAR   
);

COPY INTO WALMART_DB.RAW.STORES (
    STORE,
    TYPE,
    SIZE
)
FROM @WALMART_DB.RAW.WALMART_STAGE
FILES = ('stores.csv') -- must indicate respective file for table in s3 bucket
FILE_FORMAT = (FORMAT_NAME = 'MY_CSV_FORMAT')
ON_ERROR = 'SKIP_FILE';

-- SELECT * FROM WALMART_DB.RAW.FACT
-- LIMIT 10;

-- SELECT * FROM WALMART_DB.RAW.DEPARTMENT
-- LIMIT 10;

-- SELECT * FROM WALMART_DB.RAW.STORES
-- LIMIT 10 OFFSET 35;

-- DROP SCHEMA PC_DBT_DB.BRONZE;

-- 1. Grant database-level access
GRANT USAGE, CREATE SCHEMA ON DATABASE WALMART_DB TO ROLE PC_DBT_ROLE;

-- 2. Grant access to existing and future objects in RAW schema
GRANT USAGE ON SCHEMA WALMART_DB.RAW TO ROLE PC_DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA WALMART_DB.RAW TO ROLE PC_DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA WALMART_DB.RAW TO ROLE PC_DBT_ROLE;

-- 3. Create BRONZE schema if it doesn't exist and grant full control
CREATE SCHEMA IF NOT EXISTS WALMART_DB.BRONZE;
GRANT ALL PRIVILEGES ON SCHEMA WALMART_DB.BRONZE TO ROLE PC_DBT_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA WALMART_DB.BRONZE TO ROLE PC_DBT_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA WALMART_DB.BRONZE TO ROLE PC_DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA WALMART_DB.BRONZE TO ROLE PC_DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA WALMART_DB.BRONZE TO ROLE PC_DBT_ROLE;


-- verify bronze layer successfully deployed from dbt
SHOW VIEWS IN SCHEMA WALMART_DB.BRONZE;

SELECT * FROM WALMART_DB.BRONZE.STG_STORES LIMIT 10;
SELECT * FROM WALMART_DB.BRONZE.STG_FACT LIMIT 10;
SELECT * FROM WALMART_DB.BRONZE.STG_DEPARTMENT LIMIT 10;

-- verify silver layer successfully deployed from dbt
SELECT * FROM WALMART_DB.SILVER.INT_WALMART_SALES_JOINED LIMIT 10;

-- verify gold layer successfully deployed from dbt
-- CHECK DATE DIMENSION (SCD TYPE 1)
SELECT * FROM WALMART_DB.GOLD.WALMART_DATE_DIM LIMIT 10;

-- CHECK STORE DIMENSION (SCD TYPE 1)
SELECT * FROM WALMART_DB.GOLD.WALMART_STORE_DIM LIMIT 10;

-- CHECK FACT TABLE (SCD TYPE 2)
SELECT * FROM WALMART_DB.GOLD.WALMART_FACT_TABLE LIMIT 10;

SELECT CURRENT_USER();









    